language: python
python:
  - "2.7"
  - "3.5"
before_install:
  - cd behaviopy
install:
  - travis_wait 20 pip install -r requirements.txt
  - pip install .
script: 
  - py.test
  for f in behaviopy/examples/*.py; do python "$f"; done
