language: python
python:
  - "2.7"
  - "3.5"
install:
  - travis_wait 20 pip install -r requirements.txt
  - pip install .
script: 
  - export MPLBACKEND="agg"
  - (cd behaviopy/examples && for f in *.py ; do python "$f" ; done)
